name: DartWorkshopLafore
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: artemgalas <email@example.com>

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
  angular: ^5.0.0-alpha+13
  angular_components: ^0.9.0-beta+2
  angular_forms: ^2.0.0-beta
  angular_router: ^2.0.0-alpha+15
  color: any

dev_dependencies:
  angular_test: ^2.0.0-alpha+11
  build_runner: ^0.9.2
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.0-beta
  test: ^1.0.0
  sass_builder: ^2.0.0